<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name' => 'Gratuito',
                'slug' => 'gratuito',
                'description' => 'Ideal para quem está a começar. Experimente a plataforma gratuitamente durante 1 ano.',
                'badge_color' => 'gray',
                'icon' => 'gift',
                'price_monthly' => 0,
                'price_yearly' => 0,
                'max_hotels' => 1,
                'max_room_types_per_hotel' => 3,
                'max_images_per_hotel' => 5,
                'max_images_per_room' => 2,
                'featured_listing' => false,
                'priority_support' => false,
                'advanced_analytics' => false,
                'review_responses' => false,
                'restaurant_management' => false,
                'leisure_management' => false,
                'custom_branding' => false,
                'api_access' => false,
                'priority_search' => false,
                'promotions' => false,
                'export_reports' => false,
                'trial_days' => 365,
                'sort_order' => 1,
                'is_active' => true,
                'is_popular' => false,
                'is_free' => true,
            ],
            [
                'name' => 'Starter',
                'slug' => 'starter',
                'description' => 'Para pequenos proprietários que querem mais visibilidade e funcionalidades.',
                'badge_color' => 'blue',
                'icon' => 'rocket',
                'price_monthly' => 9900,
                'price_yearly' => 99900,
                'max_hotels' => 2,
                'max_room_types_per_hotel' => 8,
                'max_images_per_hotel' => 15,
                'max_images_per_room' => 5,
                'featured_listing' => false,
                'priority_support' => false,
                'advanced_analytics' => false,
                'review_responses' => true,
                'restaurant_management' => false,
                'leisure_management' => false,
                'custom_branding' => false,
                'api_access' => false,
                'priority_search' => false,
                'promotions' => true,
                'export_reports' => false,
                'trial_days' => 14,
                'sort_order' => 2,
                'is_active' => true,
                'is_popular' => false,
                'is_free' => false,
            ],
            [
                'name' => 'Profissional',
                'slug' => 'profissional',
                'description' => 'A escolha ideal para proprietários que querem maximizar reservas e receita.',
                'badge_color' => 'indigo',
                'icon' => 'star',
                'price_monthly' => 24900,
                'price_yearly' => 249900,
                'max_hotels' => 5,
                'max_room_types_per_hotel' => 20,
                'max_images_per_hotel' => 30,
                'max_images_per_room' => 10,
                'featured_listing' => true,
                'priority_support' => true,
                'advanced_analytics' => true,
                'review_responses' => true,
                'restaurant_management' => true,
                'leisure_management' => true,
                'custom_branding' => false,
                'api_access' => false,
                'priority_search' => true,
                'promotions' => true,
                'export_reports' => true,
                'trial_days' => 14,
                'sort_order' => 3,
                'is_active' => true,
                'is_popular' => true,
                'is_free' => false,
            ],
            [
                'name' => 'Empresarial',
                'slug' => 'empresarial',
                'description' => 'Para cadeias hoteleiras e grandes operadores. Tudo ilimitado com suporte dedicado.',
                'badge_color' => 'amber',
                'icon' => 'crown',
                'price_monthly' => 49900,
                'price_yearly' => 499900,
                'max_hotels' => 999,
                'max_room_types_per_hotel' => 999,
                'max_images_per_hotel' => 999,
                'max_images_per_room' => 999,
                'featured_listing' => true,
                'priority_support' => true,
                'advanced_analytics' => true,
                'review_responses' => true,
                'restaurant_management' => true,
                'leisure_management' => true,
                'custom_branding' => true,
                'api_access' => true,
                'priority_search' => true,
                'promotions' => true,
                'export_reports' => true,
                'trial_days' => 30,
                'sort_order' => 4,
                'is_active' => true,
                'is_popular' => false,
                'is_free' => false,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
